spring:
  config:
    import: optional:classpath:deploy.properties
  application:
    name: Task Managing System
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
