spring:
  config:
    import: optional:classpath:deploy.properties
  application:
    name: Task Managing System
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    default-property-inclusion: non_empty
  messages:
    basename: i18n/messages
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        generate_statistics: true
        cache:
          missing_cache_strategy: create
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
    resolve-extensions-properties: true
  swagger-ui:
    path: /swagger
auths:
  endpoints:
    allowed:
      /swagger/**,
      /swagger-ui/**,
      /swagger-resources/**,
      /api-docs/**,
      /auth/login/**,
      /auth/register/**
    modifiable:
      authorized:
        /tasks/**,
        /tasks/{TASK_ID}/**
  jwt:
    claims:
      issuer: ${spring.application.name}
      secret: ${JWT_HMAC_SECRET}
      expiration-millis: 600000
